# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
#    command:
#      - "-c"
#      - "shared_preload_libraries = 'pg_stat_statements'"
#      - "-c"
#      - "pg_stat_statements.track = all"
#    command:
#      - "-c"
#      - "max_connections=1000"
#      - "-c"
#      - "shared_buffers=32MB"

    environment:
    - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - local
  pghero:
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    image: ankane/pghero
    ports:
      - "8080:8080"
    networks:
      - local

volumes:
  postgresql:

networks:
  local:
